version: '2'
services:
  db:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
  
  web:
    build: .
    ports: 
      - "4500:4500"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    links: 
      - db
    command: bash -c "sleep 7 && node_modules/.bin/sequelize db:migrate && npm start"
    